#!/usr/bin/env bash

# The inputs to this script are:
#
#   1.[REPO_NAME] ...
#

# get arguments
REPO_NAME=$1

# check REPO_NAME
if [ "${REPO_NAME}" = "<REPO_NAME_HERE>" ]; then
  >&2 echo "ERROR: You need to change the value of REPO_NAME inside Dockerfile.";
  exit 1;
fi

# everything should be OK
echo "PASSED: Your build environment looks fine!";
